PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ela: <http://www.semanticweb.org/ela-ontology#>
SELECT ?compiler_name ?compiler_description ?link
WHERE
{
    ?language_placeholder ela:isCompiledWith ?compiler.
    ?compiler ela:CompilerName ?compiler_name.
    ?compiler ela:CompilerDescription ?compiler_description.
    OPTIONAL
    {
        ?compiler ela:ExternalLink ?link.
    }
}