PREFIX ela: <http://www.semanticweb.org/ela-ontology#>
# query for extracting the program examples for a given language
# the parameterized variable that must be replaced is ?language_name_to_match
SELECT ?source_code ?description
WHERE
{
	?program ela:ProgramCode ?source_code.
	?program ela:ProgramDescription ?description.
	?program ela:isExampleFor ?language.
	?language ela:LanguageName ?language_name.
	FILTER(REGEX(?language_name, ?language_name_to_match)).
}